"""remove FarePeriod from fare_definitions

Revision ID: 03883975b23f
Revises: bbcc14ec0be3
Create Date: 2025-10-30 15:15:10.268871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03883975b23f'
down_revision: Union[str, Sequence[str], None] = 'bbcc14ec0be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fare_definitions', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fare_definitions', sa.Column('period', postgresql.ENUM('PEAK', 'OFF_PEAK', name='fareperiod'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
