"""initial schema

Revision ID: 3c61d9e662c1
Revises: 5a898e26a7a2
Create Date: 2025-10-27 12:19:42.213943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c61d9e662c1'
down_revision: Union[str, Sequence[str], None] = '5a898e26a7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fare_definitions',
    sa.Column('fare_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency_type', sa.String(), nullable=True),
    sa.Column('payment_method', sa.Integer(), nullable=True),
    sa.Column('transfers', sa.Integer(), nullable=True),
    sa.Column('transfer_duration', sa.Integer(), nullable=True),
    sa.Column('period', sa.Enum('PEAK', 'OFF_PEAK', name='fareperiod'), nullable=True),
    sa.PrimaryKeyConstraint('fare_id')
    )
    op.create_index(op.f('ix_fare_definitions_fare_id'), 'fare_definitions', ['fare_id'], unique=True)
    op.create_table('routes',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('route_short_name', sa.String(), nullable=True),
    sa.Column('route_long_name', sa.String(), nullable=True),
    sa.Column('route_type', sa.Integer(), nullable=True),
    sa.Column('route_color', sa.String(), nullable=True),
    sa.Column('route_text_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_route_id'), 'routes', ['route_id'], unique=False)
    op.create_table('shapes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shape_id', sa.String(), nullable=False),
    sa.Column('shape_pt_lat', sa.Float(), nullable=False),
    sa.Column('shape_pt_lon', sa.Float(), nullable=False),
    sa.Column('shape_pt_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stages',
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('stop_lat', sa.Float(), nullable=False),
    sa.Column('stop_lon', sa.Float(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_index(op.f('ix_stages_stop_id'), 'stages', ['stop_id'], unique=False)
    op.create_table('fare_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fare_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('origin_id', sa.String(), nullable=True),
    sa.Column('destination_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fare_id'], ['fare_definitions.fare_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stop_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stages.stop_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_stop_id', sa.String(), nullable=False),
    sa.Column('to_stop_id', sa.String(), nullable=False),
    sa.Column('transfer_type', sa.Integer(), nullable=True),
    sa.Column('min_transfer_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_stop_id'], ['stages.stop_id'], ),
    sa.ForeignKeyConstraint(['to_stop_id'], ['stages.stop_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_table('stop_times')
    op.drop_table('fare_rules')
    op.drop_index(op.f('ix_stages_stop_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_table('shapes')
    op.drop_index(op.f('ix_routes_route_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_fare_definitions_fare_id'), table_name='fare_definitions')
    op.drop_table('fare_definitions')
    # ### end Alembic commands ###
