"""test column add

Revision ID: 6c5c2a97ba43
Revises: 3c61d9e662c1
Create Date: 2025-10-27 12:24:02.021260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5c2a97ba43'
down_revision: Union[str, Sequence[str], None] = '3c61d9e662c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fare_definitions', sa.Column('test_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fare_definitions', 'test_id')
    # ### end Alembic commands ###
