"""test column deleted

Revision ID: 9d131592f751
Revises: 6c5c2a97ba43
Create Date: 2025-10-27 12:28:03.448348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d131592f751'
down_revision: Union[str, Sequence[str], None] = '6c5c2a97ba43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fare_definitions', 'test_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fare_definitions', sa.Column('test_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
