"""Add new node Edges model

Revision ID: a82244fba31b
Revises: 9d131592f751
Create Date: 2025-11-01 09:51:13.963922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82244fba31b'
down_revision: Union[str, Sequence[str], None] = '9d131592f751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edges',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('reverse_cost', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=False)
    op.add_column('fare_definitions', sa.Column('period', sa.Enum('PEAK', 'OFF_PEAK', name='fareperiod'), nullable=True))
    op.add_column('stages', sa.Column('zone_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('stop_times_route_id_fkey'), 'stop_times', type_='foreignkey')
    op.drop_column('stop_times', 'route_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stop_times', sa.Column('route_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('stop_times_route_id_fkey'), 'stop_times', 'routes', ['route_id'], ['route_id'])
    op.drop_column('stages', 'zone_id')
    op.drop_column('fare_definitions', 'period')
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    # ### end Alembic commands ###
