"""update models and relationships

Revision ID: bbcc14ec0be3
Revises: 9d131592f751
Create Date: 2025-10-29 12:04:27.312767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcc14ec0be3'
down_revision: Union[str, Sequence[str], None] = '9d131592f751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'zone_id')
    op.add_column('stop_times', sa.Column('route_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'stop_times', 'routes', ['route_id'], ['route_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop_times', type_='foreignkey')
    op.drop_column('stop_times', 'route_id')
    op.add_column('stages', sa.Column('zone_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
