"""Add route_id column on edge

Revision ID: f82cde9a7fa4
Revises: 28e05bbaca21
Create Date: 2025-11-01 20:17:31.560137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82cde9a7fa4'
down_revision: Union[str, Sequence[str], None] = '28e05bbaca21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('route_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'route_id')
    # ### end Alembic commands ###
